PaulSchweizer/flowpipe

.travis.yml
=> updated travis.yml for autodeploy on tag

.travis.yml, README.md, setup.py
Also added:
- install instructions to readme
- pypi version badge to readme
- readme as pypi long description
Closes #38
=> travis multiple version fix

.gitignore, .travis.yml, flowpipe/graph.py, flowpipe/node.py, flowpipe/plug.py, tests/test_graph.py, tests/test_node.py, tests/test_plugs.py
Provides this enhancement, description in the ticket: https://github.com/PaulSchweizer/flowpipe/issues/37
=> #37 compound plugs 

README.md
Just a fix for the readme example.
=> Fixed readme example

flowpipe/node.py, flowpipe/plug.py, flowpipe/utilities.py, tests/test_convert_function_to_node.py, tests/test_node.py, tests/test_plugs.py
I found a few bugs with serialization and also added an exception if internal names are used for input plug names with the ```@Node``` decorator. Would be cool if you could give it a read when your time permits, thanks in advance!
=> Small bug fixes

flowpipe/graph.py, tests/test_graph.py
Removing the exception as it appears that it can be falsely triggered.
I have not fully investigated this yet though. 
@neuneck, was there a reason for putting in that exception? I can't recall but 
@Onandon11, would you be able to test these changes in your local environment?
=> Removed the exception

flowpipe/node.py, tests/test_convert_function_to_node.py
@Onandon11, please take a look at this, regarding your ticket #71
=> Use getfullargspec

flowpipe/plug.py, tests/test_plugs.py
In response to your ticket @Onandon11: https://github.com/PaulSchweizer/flowpipe/issues/72
=> SubOutputs inform their parent when values set

flowpipe/graph.py, tests/test_graph.py, tests/test_multiprocessing.py
This was surprisingly straight forward to implement (thanks @Onandon11 for bringing up this topic earlier today and providing the inspiration to look into this again!)
I haven't tested it a whole lot or run in production though so it will definitely need some adjustment.
@neuneck  and @Onandon11 please give it a try when you have a moment and let me know what you think.
Here's the test code I ran:
```python
from flowpipe.node import INode, Node
from flowpipe.plug import InputPlug, OutputPlug
from flowpipe.graph import Graph
class HireWorkers(INode):
"""A node can be derived from the INode interface.
The plugs are defined in the init method.
The compute method received the inputs from any connected upstream nodes.
"""
def __init__(self, amount=None, **kwargs):
super(HireWorkers, …
```
=> Multiprocessing

flowpipe/graph.py
In response to #93
Using the same logic as with multiprocessing to keep the two in line
=> Only return after all threads are finished

examples/house_and_birthday.py, examples/vfx_render_farm_conversion.py, examples/vfx_rendering.py, examples/world_clock.py, flowpipe/__init__.py
Graph, Node, INode, InputPlug, OutputPlug, SubInputPlug, SubOutputPlug available at the package level.
=> Made most common object available at the package level.

flowpipe/plug.py, flowpipe/utilities.py, tests/test_node.py, tests/test_plugs.py, tests/test_utilities.py
Added a hashing mechanism to determine whether a plug should be set dirty on a value assignment
=> Added logic to value.setter to determine whether plug is dirty

README.md
When I updated the examples, I missed the one in the README.
=> Updated the example in the README to new import structure

flowpipe/__init__.py, flowpipe/graph.py, flowpipe/node.py, tests/test_convert_function_to_node.py, tests/test_graph.py, tests/test_node.py
I still have to fix the tests, but this is how I imagine the functionality to look like and wanted to get this out before the weekend.
=> Merge serialization revamp

flowpipe/__init__.py, flowpipe/graph.py, setup.py, tests/test_multiprocessing.py
The issue was that a previous node could be finished evaluating but it's values were not yet updated because upstream ready was only checking whether the process was finished
=> upstream only ready when evaluated and removed from list

flowpipe/utilities.py
=> Fixed unhasable values to be caught by if statement.

contributing.md, tests/conftest.py, tests/test_graph.py
=> testing conftest.py, instructions to run tests

contributing.md, tests/conftest.py, tests/test_graph.py
=> Reuse more pytest fixtures

flowpipe/node.py, flowpipe/plug.py, tests/test_convert_function_to_node.py
=> Make it possible to add sub outputs in Node

.gitignore, flowpipe/graph.py, requirements.txt, tests/test_graph.py
Had to also slightly change a string formatting in tests because my editor trims trailing white space
Resolves #116
=> Delete nodes, resolves #116

flowpipe/graph.py
I had some pain with our complicated graph (nearing 30 nodes, that listen to s3 storage, make calls to 12 different microservices, ...) and added some useful stuff for debugging the threaded evaluation, which I think makes sense to merge back into the master, so everyone can benefit from it.
Added a debug log line on iterations in the thread submission loop;
Added a check for a deadlock situation (which sometimes ocurs if a node does not turn clean after being evaluated);
Made the running_futures object into a dictionary to be able to track the state of the flow more easily when debugging (by having the names of the running nodes as keys).
=> Better debug tooling for threaded evaluation

flowpipe/node.py, tests/test_graph.py, tests/test_node.py
Also indicate the abbreviatiation of long values with "..."
=> Show the output values of plugs in str representation

flowpipe/graph.py, tests/test_graph.py
Resolves: #114 
Please take a look if this is a solution for you @Onandon11 
The flag data_persistance in Graph.evaluate can now be set. It sets the value of all plugs with a connection to None after the entire graph has been evaluated to remove the instance references.
Let me know what you think.
Another approach would be to do this during evaluation?
=> First attempt at data persistancy

examples/dynamic_plug_names.py
I finally got around to adding an example based on the dynamic plug name pattern I've been using for a while now.
Closes https://github.com/PaulSchweizer/flowpipe/issues/106
=> Added an example for dynamic plug names

flowpipe/__init__.py, flowpipe/graph.py, flowpipe/plug.py, tests/test_inputpluggroup.py
This closes #142 
The test should illustrate how it works. Let me know if you had a different functionality in mind
=> Introducing InputPlugGroup

flowpipe/graph.py, flowpipe/node.py, flowpipe/plug.py, tests/test_graph.py, tests/test_inputpluggroup.py, tests/test_node.py
Resolves https://github.com/PaulSchweizer/flowpipe/issues/150
=> Made InputPlugGroups behave move closely like InputPlugs

flowpipe/graph.py, flowpipe/node.py
Some of the code assembling the downstream and upstream nodes as well as calculation the evaluation matrix was not ideal and could lead to ridiculously long execution times. This PR is fixing it.
=> Improve assembling of down/upstream nodes and evaluation matrix creation

flowpipe/graph.py, flowpipe/node.py, tests/test_graph.py, tests/test_node.py
Since I had this mapped out in my head already, I went ahead and made the evaluation matrix computation iterative.
=> Rewrote evaluation matrix computation iteratively

README.md
adding refrence projects to the docs page
=> adding project reference links

examples/nested_graphs.py, flowpipe-for-vfx-pipelines.md
fixing typo in flowpipe for vfx pipelines md file
fix typo in nested graphs example
=> Docs and Example Typo Fixing
